apiVersion: v1
kind: Pod
metadata:
        name: wish
spec:
        containers:
                - name: abc
                  image: nginx
                  resources:
                          requests:
                            memory: "400Mi"
                          limits:
                            memory: "800Mi"
                
