apiVersion: v1
kind: ReplicationController
metadata:
        name: myapp
spec:
        replicas: 30
        template:
                metadata:
                        name: abc
                        labels:
                                app: webserver
                spec:
                        containers:
                                - name: mywebsite
                                  image: nginx
