apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: default
subjects:
- kind: User
  name: wish
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role # this must be the  role/custer role
  name: pod-reader # this must be the name of the role / custer role
  apiGroup: rbac.authorization.k8s.io
