apiVersion: v1
kind: Service
metadata:
        name: my-website-svc
spec:
        selector:
                type: frontend
        type: NodePort
        ports:
               - targetPort: 80
                 port: 80
                 nodePort: 31080
