apiVersion: v1
kind: Service
metadata:
        name: my-clusterip-svc
spec:
        selector:
                type: frontend
        type: ClusterIP
        ports:
               - targetPort: 80
                 port: 80
                 
