apiVersion: v1
kind: Service
metadata:
        name: mywp-svc
        namespace: project
spec:
        selector:
                app: wordpress
        type: NodePort
        ports:
                - protocol: TCP
                  targetPort: 80
                  port: 80
                  nodePort: 30080 
                



